anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
xferlog_enable=YES
syslog_enable=NO
log_ftp_protocol=YES
xferlog_std_format=NO
vsftpd_log_file=/var/log/ftp/vsftpd.log
xferlog_file=/var/log/ftp/xferlog.log
connect_from_port_20=YES
listen=YES
listen_ipv6=NO
pam_service_name=vsftpd
seccomp_sandbox=NO
allow_writeable_chroot=YES
chroot_local_user=YES
chroot_list_enable=NO
local_root=/var/www/html
passwd_chroot_enable=NO
hide_ids=YES
pasv_enable=YES
