Alias /phpmyadmin /opt/phpmyadmin

<Directory /opt/phpmyadmin>
    Options FollowSymLinks
    DirectoryIndex index.php
    AllowOverride All
    Require all granted
    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://127.0.0.1:9000"
    </FilesMatch>
</Directory>

# Separate phpMyAdmin log files
<IfModule mod_log_config.c>
    SetEnvIf Request_URI "^/phpmyadmin" pma_request
    CustomLog /var/log/phpmyadmin/access.log combined env=pma_request
    ErrorLog /var/log/phpmyadmin/error.log
</IfModule>
